(dp1
S'output'
p2
S"<type 'exceptions.MemoryError'> "
p3
sS'layer'
p4
S'C:\\Users\\unificace\\unificace\\web2py\\applications\\init\\models\\db.py'
p5
sS'code'
p6
S'<code object <module> at 00000000027457B0, file "C:\\Users\\unificace\\unificace\\web2py\\applications\\init\\models\\db.py", line 14>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File ".\\gluon\\restricted.py", line 219, in restricted\n  File "C:\\Users\\unificace\\unificace\\web2py\\applications\\init\\models\\db.py", line 194, in <module>\n    auth.define_tables(username=True, signature=False)\n  File ".\\gluon\\tools.py", line 2216, in define_tables\n  File ".\\gluon\\authapi.py", line 424, in define_tables\n    fake_migrate=fake_migrate))\n  File "C:\\Users\\unificace\\unificace\\web2py\\gluon\\packages\\dal\\pydal\\base.py", line 586, in define_table\n  File "C:\\Users\\unificace\\unificace\\web2py\\gluon\\packages\\dal\\pydal\\base.py", line 598, in lazy_define_table\n  File "C:\\Users\\unificace\\unificace\\web2py\\gluon\\packages\\dal\\pydal\\objects.py", line 290, in __init__\n  File "C:\\Users\\unificace\\unificace\\web2py\\gluon\\packages\\dal\\pydal\\objects.py", line 627, in __setattr__\n  File "C:\\Users\\unificace\\unificace\\web2py\\gluon\\packages\\dal\\pydal\\objects.py", line 614, in __setitem__\nMemoryError\n'
p11
s.