(dp1
S'output'
p2
S"<type 'exceptions.MemoryError'> "
p3
sS'layer'
p4
S'C:\\Users\\unificace\\unificace\\web2py\\applications\\init\\models\\db.py'
p5
sS'code'
p6
S'<code object <module> at 000000000222F7B0, file "C:\\Users\\unificace\\unificace\\web2py\\applications\\init\\models\\db.py", line 14>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File ".\\gluon\\restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "C:\\Users\\unificace\\unificace\\web2py\\applications\\init\\models\\db.py", line 92, in <module>\n    auth = Auth(db, host_names=myconf.get(\'host.names\'))\n  File ".\\gluon\\tools.py", line 1861, in __init__\n    self.define_signature()\n  File ".\\gluon\\authapi.py", line 224, in define_signature\n    label=T(\'Modified By\'),  ondelete=ondelete))\n  File "C:\\Users\\unificace\\unificace\\web2py\\gluon\\packages\\dal\\pydal\\objects.py", line 339, in __init__\n    reserved = dir(Table) + [\'fields\']\nMemoryError\n'
p11
s.